### ISSUE TITLE
Should `basic_json` be constructible from `nulljson_t`?

### ISSUE THREAD

**Issue by frederick-vs-ja** [YexuanXiao/basic_json#10]
Currently we can't directly construct `basic_json` from `nulljson_t`, but there's a workaround.
```C++
// basic_json<...> json{nulljson}; // error
basic_json<...> json; 
json.slice() = nulljson;
```

Is this intended?

**Comment by YexuanXiao** [comment]
No, it wasn’t intentional; it needs to be fixed.
